$ENV{TEXINPUTS} = "../springer-nature-latex-template/sn-article-template//;" . ($ENV{TEXINPUTS} || "");
$ENV{BSTINPUTS} = "../springer-nature-latex-template/sn-article-template/bst//;" . ($ENV{BSTINPUTS} || "");

$pdf_mode = 1;
$pdflatex = "pdflatex -interaction=nonstopmode -halt-on-error %O %S";

$clean_ext .= " acn acr alg aux bbl bcf blg fdb_latexmk fls glg glo gls idx ilg ind ist lof log lot out run.xml synctex.gz toc";
