import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";
import { fileURLToPath } from "node:url";

const desktopHtml = await readFile(
  fileURLToPath(new URL("../index.html", import.meta.url)),
  "utf8",
);
const desktopSource = await readFile(
  fileURLToPath(new URL("../src/desktop-app.js", import.meta.url)),
  "utf8",
);
const companionHtml = await readFile(
  fileURLToPath(new URL("../companion/index.html", import.meta.url)),
  "utf8",
);
const companionSource = await readFile(
  fileURLToPath(new URL("../src/companion-app.js", import.meta.url)),
  "utf8",
);
const nativeSource = await readFile(
  fileURLToPath(new URL("../../src-tauri/src/lib.rs", import.meta.url)),
  "utf8",
);
const mainCapability = JSON.parse(await readFile(
  fileURLToPath(new URL("../../src-tauri/capabilities/runner-main.json", import.meta.url)),
  "utf8",
));
const inspectionPermission = await readFile(
  fileURLToPath(new URL("../../src-tauri/permissions/autogenerated/inspect_prepared_execution.toml", import.meta.url)),
  "utf8",
);
const audioPreparationPermission = await readFile(
  fileURLToPath(new URL("../../src-tauri/permissions/autogenerated/prepare_first_audio_block.toml", import.meta.url)),
  "utf8",
);

test("desktop package selection is a local native operation with a bounded plan projection", () => {
  assert.match(desktopHtml, /id="select-session-manifest"/u);
  assert.match(desktopHtml, /id="package-block-list"/u);
  assert.match(desktopHtml, /id="package-block-count"/u);
  assert.match(desktopHtml, /id="package-mode"/u);
  assert.match(desktopHtml, /id="inspect-prepared-execution"/u);
  assert.match(desktopHtml, /id="execution-inspection-detail"/u);
  assert.match(desktopHtml, /id="prepare-first-audio-block"/u);
  assert.match(desktopHtml, /id="prepared-audio-detail"/u);
  assert.match(desktopHtml, /id="prepared-audio-status"/u);
  assert.match(desktopHtml, /id="execution-event-count"/u);
  assert.match(desktopSource, /await api\.selectPreparedSession\(\)/u);
  assert.match(desktopSource, /await api\.inspectPreparedExecution\(\)/u);
  assert.match(desktopSource, /await api\.prepareFirstAudioBlock\(\)/u);
  assert.match(desktopSource, /native V1 provenance checks/u);
  assert.match(desktopSource, /document\.createElement\("li"\)/u);
  assert.doesNotMatch(desktopSource, /package-block-list[\s\S]{0,200}innerHTML/u);
});

test("native audio preparation is an explicit local no-argument non-executable preload", () => {
  assert.match(nativeSource, /async fn prepare_first_audio_block\(\s*window: tauri::WebviewWindow,\s*state: tauri::State<'_, AppRuntime>,\s*\)/u);
  assert.match(nativeSource, /prepare_first_audio_block[\s\S]+require_main_window\(&window\)/u);
  assert.match(audioPreparationPermission, /commands\.allow = \["prepare_first_audio_block"\]/u);
  assert.ok(mainCapability.permissions.includes("allow-prepare-first-audio-block"));
  assert.match(desktopSource, /schema === "pps-runner-prepared-audio-summary\.v1"/u);
  assert.match(desktopSource, /scope === "pcm-cache-only"/u);
  assert.match(desktopSource, /qualification === "unqualified"/u);
  assert.match(desktopSource, /candidate\.executable === false/u);
  assert.match(desktopSource, /!preparedExecution[\s\S]{0,100}\|\| active/u);
  assert.match(desktopSource, /const invalidatesPreparedAudio = active[\s\S]{0,180}!next\.package_verified[\s\S]{0,100}!preparedExecution/u);
  assert.match(desktopSource, /if \(preparedAudio && invalidatesPreparedAudio\) renderPreparedAudio\(null\)/u);
  assert.doesNotMatch(desktopSource, /prepareFirstAudioBlock\([^)]/u);
  assert.doesNotMatch(companionHtml, /prepare-first-audio-block/u);
  assert.doesNotMatch(companionSource, /prepareFirstAudioBlock|prepare_first_audio_block/u);
});

test("native package selection stays disabled in browser preview and during active phases", () => {
  assert.match(desktopSource, /api\.kind !== "tauri-native" \|\| active/u);
  assert.match(desktopSource, /"instruction_gate", "running", "paused", "stopping"/u);
  assert.doesNotMatch(desktopSource, /prepare-demo-button"\]\.hidden/u);
  assert.match(desktopSource, /button\.disabled = !allowed\.has\(button\.dataset\.action\)/u);
});

test("native package selection owns its picker and exposes no caller path capability", () => {
  assert.match(nativeSource, /async fn select_prepared_session\(\s*app: tauri::AppHandle,\s*window: tauri::WebviewWindow,\s*state: tauri::State<'_, AppRuntime>,\s*\)/u);
  assert.match(nativeSource, /require_main_window\(&window\)/u);
  assert.match(nativeSource, /app\.dialog\(\)[\s\S]{0,240}\.pick_file/u);
  assert.match(nativeSource, /VerificationRequest::new\(&manifest_path\)/u);
  assert.ok(mainCapability.permissions.includes("allow-select-prepared-session"));
  assert.ok(!mainCapability.permissions.some((permission) => permission.startsWith("dialog:")));
});

test("native schedule inspection is explicit, path-free, and cannot authorize execution", () => {
  assert.match(nativeSource, /async fn inspect_prepared_execution\(/u);
  assert.match(nativeSource, /require_main_window\(&window\)/u);
  assert.match(inspectionPermission, /commands\.allow = \["inspect_prepared_execution"\]/u);
  assert.ok(mainCapability.permissions.includes("allow-inspect-prepared-execution"));
  assert.match(desktopSource, /inspectionScope/u);
  assert.match(desktopSource, /timingQualification/u);
  assert.match(desktopSource, /executable/u);
  assert.match(desktopSource, /Audio and execution remain disabled/u);
  assert.doesNotMatch(desktopSource, /inspectPreparedExecution\([^)]/u);
});
