/**
 * Proposed paper-dependent target parameter taxonomy for publication recreation.
 *
 * This is deliberately finer-grained than the current 25-field literature
 * audit and the 15/19-field profile-recreation gate. Each leaf is intended to
 * receive its own source-review status. These are target requirements, not
 * claims about fields accepted by the current serializer. Repeating entities
 * are represented as arrays in evidence/value stores, not by duplicating
 * semantic columns.
 */

const group = (id, label, segment, prefix, keys, options = {}) => ({
  id,
  label,
  segment,
  prefix,
  keys,
  repeatableEntity: options.repeatableEntity || "",
  toolkitPath: options.toolkitPath || "",
  defaultSupport: options.defaultSupport || "not_assessed",
});

export const PAPER_PARAMETER_GROUPS = [
  group(
    "study_design",
    "Study and profile design",
    "0",
    "target.study",
    [
      "study_design_type",
      "population_scope",
      "planned_sample_n",
      "participant_code_policy",
      "group_labels",
      "condition_labels",
      "within_subject_factors",
      "between_subject_factors",
      "session_timepoints",
      "assignment_counterbalancing",
      "inclusion_criteria",
      "exclusion_criteria",
      "eligibility_screening",
      "intervention_training",
      "tool_condition",
      "locomotion_condition",
      "social_clinical_context",
    ],
    {
      repeatableEntity: "group[] / condition[] / session[]",
      toolkitPath: "study_templates/*.json::{reference_parameters,design}; runner participant manifest",
      defaultSupport: "freeform_metadata_only",
    },
  ),
  group(
    "source_definition",
    "Auditory and source definition",
    "1",
    "target.sources",
    [
      "stimulus_modality_set",
      "source_count",
      "source_labels",
      "source_kind",
      "auditory_stimulus_type",
      "auditory_condition_labels",
      "noise_type",
      "tone_type",
      "tone_frequency_hz",
      "semantic_valence_class",
      "source_origin_generation_method",
      "generation_software_version",
      "source_profile",
      "burst_count_mode",
      "burst_count",
      "burst_duration_ms",
      "burst_rise_fall_ms",
      "burst_period_ms",
      "burst_onset_ms",
      "burst_active_window_ms",
      "burst_spacing_policy",
      "source_sample_rate_hz",
      "source_bit_depth",
      "source_channels",
      "source_duration_ms",
      "source_gain_linear",
      "import_render_mode",
      "source_motion_mode",
      "source_equivalence_policy",
    ],
    {
      repeatableEntity: "source[]",
      toolkitPath: "design.{noises,custom_looming_files,prestimulus_files}; source profile metadata; Segment 1 assets",
      defaultSupport: "backend_schema_only",
    },
  ),
  group(
    "trajectory_orientation",
    "Trajectory and orientation",
    "1",
    "target.trajectories",
    [
      "trajectory_count",
      "trajectory_labels",
      "trajectory_family",
      "trajectory_direction",
      "coordinate_mode",
      "coordinate_frame",
      "start_distance_cm",
      "end_distance_cm",
      "start_xyz_m",
      "end_xyz_m",
      "path_length_m",
      "speed_mps",
      "movement_duration_ms",
      "azimuth_start_deg",
      "azimuth_end_deg",
      "elevation_start_deg",
      "elevation_end_deg",
      "pre_hold_ms",
      "post_hold_ms",
      "inverse_square_enabled",
      "attenuation_gain_law",
      "propagation_delay_policy",
      "body_anchor",
      "body_part",
      "body_side",
      "spatial_hemifield",
      "body_relative_axis",
      "participant_posture",
      "head_trunk_facing",
      "gaze_fixation_eyes_policy",
      "source_room_positions",
      "movement_implementation",
      "distance_or_soa_anchor_table",
    ],
    {
      repeatableEntity: "trajectory[] / source-room position[]",
      toolkitPath: "design.trajectory; row/source trajectory_snapshot; Segment 1 trajectory inventory",
      defaultSupport: "backend_schema_only",
    },
  ),
  group(
    "renderer_loudness_visual_mr",
    "Renderer, loudness, visual, and mixed-reality context",
    "1",
    "target.rendering",
    [
      "audio_output_mode",
      "renderer_engine",
      "renderer_version",
      "sofa_hrir_asset",
      "hrtf_database",
      "hrtf_subject_id",
      "hrtf_filter_id",
      "near_field_compensation",
      "ild_itd_policy",
      "headphones_model",
      "audio_interface_model",
      "speaker_array_id",
      "speaker_model",
      "speaker_count",
      "speaker_array_layout",
      "speaker_switch_sequence",
      "speaker_switch_times_ms",
      "speaker_switch_channels",
      "speaker_switch_gains",
      "speaker_source_channel",
      "room_acoustics",
      "reverb_brir_policy",
      "drr_iacc_policy",
      "renderer_equivalence_boundary",
      "level_mode",
      "level_calibration_mode",
      "level_calibration_status",
      "start_spl_db",
      "end_spl_db",
      "instruction_offset_db",
      "gain_envelope_shape",
      "hold_level_policy",
      "level_calibration_window_ms",
      "estimated_full_scale_spl_db",
      "peak_ceiling_dbfs",
      "distance_gain_policy",
      "level_setting_hardware_policy",
      "visual_stimulus_type",
      "visual_motion_profile",
      "visual_start_distance_cm",
      "visual_end_distance_cm",
      "visual_speed_cm_s",
      "visual_duration_ms",
      "visual_renderer_engine",
      "visual_display_device",
      "mixed_reality_context",
      "body_rendering_mode",
      "audiovisual_synchrony_policy",
      "mixed_reality_equivalence_boundary",
    ],
    {
      repeatableEntity: "renderer[] / speaker[] / visual source[]",
      toolkitPath: "design trajectory/source metadata; loudness.py; Segment 1 renderer manifests; free-form reference_parameters",
      defaultSupport: "backend_schema_only",
    },
  ),
  group(
    "sequence_task",
    "Trial sequence and task",
    "2",
    "target.trial_sequence",
    [
      "trial_row_count",
      "row_ids",
      "row_labels",
      "row_order",
      "row_audio_tactile_percentage",
      "row_catch_percentage",
      "row_baseline_percentage",
      "row_soa_overrides_ms",
      "row_spatial_overrides_cm",
      "sequence_elements",
      "source_alternatives",
      "sequence_variant_count",
      "sequence_variant_keys",
      "jitter_values_ms",
      "jitter_randomized",
      "iti_policy",
      "iti_values_or_range_ms",
      "iti_distribution",
      "pre_sound_silence_ms",
      "post_sound_silence_ms",
      "foreperiod_ms",
      "condition_intermixing",
      "blocked_or_random_order",
      "task_sequence_rules",
      "hazard_control_policy",
      "expectancy_control_role",
    ],
    {
      repeatableEntity: "trial_row[] / sequence_variant[] / sequence_element[]",
      toolkitPath: "design.protocol.trial_strips; Segment 2 trial-sequence manifests and GUI",
      defaultSupport: "backend_schema_only",
    },
  ),
  group(
    "tactile_soa_baseline_catch",
    "Tactile, SOA, baseline, and catch",
    "3",
    "target.tactile_protocol",
    [
      "tactile_present",
      "tactile_modality",
      "stimulator_model",
      "tactile_site",
      "tactile_body_anchor",
      "tactile_side",
      "tactile_channel",
      "channel_map",
      "cue_duration_ms",
      "pulse_duration_ms",
      "waveform_shape",
      "frequency_hz",
      "amplitude",
      "intensity",
      "intensity_unit",
      "calibration_method",
      "threshold_reference",
      "electrode_site",
      "tactile_source_or_delivery",
      "external_trigger_required",
      "external_trigger_modality",
      "external_trigger_role",
      "external_trigger_code",
      "external_trigger_tolerance_ms",
      "external_trigger_channel",
      "soa_values_ms",
      "soa_reference_anchor",
      "soa_sign_convention",
      "spatial_values_cm",
      "pair_spatial_values_with_soas",
      "distance_at_touch_values_cm",
      "baseline_enabled",
      "baseline_strategy",
      "baseline_soa_values_ms",
      "baseline_timing_reference",
      "baseline_custom_trial_mode",
      "catch_enabled",
      "catch_type",
      "auditory_only_enabled",
    ],
    {
      repeatableEntity: "tactile site/channel[] / SOA-distance pair[]",
      toolkitPath: "design.protocol tactile/SOA/baseline/catch fields; row metadata; session_runner.py",
      defaultSupport: "backend_schema_only",
    },
  ),
  group(
    "repetition_counts",
    "Repetition and trial counts",
    "4",
    "target.trial_pool",
    [
      "repetitions_per_condition",
      "repetition_defaults_by_family",
      "repetition_overrides_by_folder",
      "repetition_overrides_by_file",
      "fractional_repetition_policy",
      "fractional_balance_seed",
      "exact_family_counts",
      "baseline_count_exact",
      "baseline_percentage",
      "catch_count_exact",
      "catch_percentage",
      "auditory_only_count_exact",
      "auditory_only_percentage",
      "catch_crosses_sequence_variants",
      "baseline_crosses_sequence_variants",
      "auditory_only_crosses_sequence_variants",
      "total_trial_count",
      "reported_or_target_playback_duration_s",
    ],
    {
      repeatableEntity: "trial family[] / source file[]",
      toolkitPath: "design.protocol repetition/count fields; Segment 4 trial-pool manifest",
      defaultSupport: "backend_schema_only",
    },
  ),
  group(
    "block_design",
    "Block design",
    "5",
    "target.block_design",
    [
      "block_count",
      "block_labels",
      "block_stimulus_types",
      "repeat_trial_pool_per_block",
      "distribute_trial_pool_across_blocks",
      "trial_randomization_strategy",
      "block_order_randomization",
      "max_consecutive_same_trial_type",
      "row_order_constraints",
      "within_family_queue_policy",
      "condition_blocking_or_intermixing",
      "random_seed",
      "per_block_trial_counts",
      "per_block_duration_estimates",
    ],
    {
      repeatableEntity: "block[]",
      toolkitPath: "design.protocol block settings; Segment 5 block CSV preview/manifests",
      defaultSupport: "first_class_gui",
    },
  ),
  group(
    "profile_finalization",
    "Profile finalization, instructions, and order",
    "6",
    "target.profile_finalization",
    [
      "part_count",
      "part_labels",
      "part_block_membership",
      "instruction_slots_enabled",
      "instruction_slot_labels",
      "instruction_audio_identity",
      "instruction_continue_modes",
      "instruction_delay_ms",
      "instruction_button_labels",
      "participant_order_algorithm",
      "participant_order_version",
      "participant_order_seed",
      "order_preview_count",
      "profile_finalization_policy",
    ],
    {
      repeatableEntity: "part[] / instruction_slot[] / preview participant[]",
      toolkitPath: "Segment 6 profile validation/save and participant-order preview",
      defaultSupport: "first_class_gui",
    },
  ),
  group(
    "runtime_task_hardware",
    "Runtime task, response, and hardware",
    "runtime",
    "target.runtime",
    [
      "response_required_by_trial_type",
      "expected_response",
      "response_rule",
      "target_role",
      "response_mode",
      "response_choice_set",
      "correct_response",
      "response_scoring_policy",
      "response_capture_device",
      "response_input_modality",
      "voice_key_enabled",
      "voice_key_response_label",
      "voice_key_threshold",
      "voice_key_latency_correction_ms",
      "response_window_anchor",
      "response_window_min_ms",
      "response_window_max_ms",
      "online_timeout_ms",
      "correctness_rule",
      "audio_device_driver_route",
      "output_channel_mapping",
      "playback_output_12_percent",
      "playback_output_34_percent",
    ],
    {
      repeatableEntity: "trial type[] / response choice[] / output channel[]",
      toolkitPath: "session_runner.py; runner row metadata; hardware/preflight manifest",
      defaultSupport: "runtime_only",
    },
  ),
  group(
    "analysis_policy",
    "Analysis policy and PPS visualization",
    "analysis",
    "target.analysis",
    [
      "primary_outcome",
      "primary_analysis_inclusion_rule",
      "topup_analysis_handling",
      "aggregation_mode",
      "grouping_factors",
      "baseline_correction_method",
      "fit_metric_fallback",
      "candidate_models",
      "model_selection_criterion",
      "min_points_linear_log",
      "min_points_sigmoid",
      "sigmoid_boundary_definition",
      "analysis_outlier_rule",
      "alpha",
      "nuisance_terms",
      "proximity_coding",
      "quality_gate_criteria",
      "uncertainty_metric",
      "pps_visualization_forms",
    ],
    {
      repeatableEntity: "analysis outcome[] / model[] / visualization[]",
      toolkitPath: "session_analysis.py; condition-lens analysis; exported analysis manifests",
      defaultSupport: "analysis_only",
    },
  ),
];

const parent = (keys, ...parents) => keys.map((key) => [key, parents]);

const CURRENT_AUDIT_PARENT_ENTRIES = [
  ...parent(
    [
      "stimulus_modality_set",
      "auditory_stimulus_type",
      "noise_type",
      "tone_type",
      "tone_frequency_hz",
      "semantic_valence_class",
    ],
    "stimulus_type",
  ),
  ...parent(
    [
      "source_kind",
      "source_origin_generation_method",
      "generation_software_version",
      "source_profile",
      "source_sample_rate_hz",
      "source_bit_depth",
      "source_channels",
      "import_render_mode",
      "source_equivalence_policy",
    ],
    "source_provenance",
  ),
  ...parent(["source_count", "trajectory_count"], "trajectory_count"),
  ...parent(["source_labels", "auditory_condition_labels", "source_motion_mode"], "auditory_conditions"),
  ...parent(
    [
      "trajectory_labels",
      "trajectory_family",
      "trajectory_direction",
      "coordinate_mode",
      "coordinate_frame",
      "start_distance_cm",
      "end_distance_cm",
      "start_xyz_m",
      "end_xyz_m",
      "path_length_m",
      "azimuth_start_deg",
      "azimuth_end_deg",
      "elevation_start_deg",
      "elevation_end_deg",
      "body_anchor",
      "body_part",
      "body_side",
      "spatial_hemifield",
      "body_relative_axis",
      "participant_posture",
      "head_trunk_facing",
      "gaze_fixation_eyes_policy",
      "source_room_positions",
      "movement_implementation",
      "distance_or_soa_anchor_table",
    ],
    "trajectory_path",
  ),
  ...parent(["speed_mps", "visual_speed_cm_s"], "stimulus_speed"),
  ...parent(
    [
      "burst_count_mode",
      "burst_count",
      "burst_duration_ms",
      "burst_rise_fall_ms",
      "burst_period_ms",
      "burst_onset_ms",
      "burst_active_window_ms",
      "burst_spacing_policy",
      "source_duration_ms",
      "movement_duration_ms",
      "pre_hold_ms",
      "post_hold_ms",
      "visual_duration_ms",
    ],
    "stimulus_duration",
  ),
  ...parent(
    [
      "source_gain_linear",
      "inverse_square_enabled",
      "attenuation_gain_law",
      "level_mode",
      "level_calibration_mode",
      "level_calibration_status",
      "start_spl_db",
      "end_spl_db",
      "instruction_offset_db",
      "gain_envelope_shape",
      "hold_level_policy",
      "level_calibration_window_ms",
      "estimated_full_scale_spl_db",
      "peak_ceiling_dbfs",
      "distance_gain_policy",
      "level_setting_hardware_policy",
    ],
    "gain_envelope",
  ),
  ...parent(
    [
      "propagation_delay_policy",
      "audio_output_mode",
      "renderer_engine",
      "renderer_version",
      "sofa_hrir_asset",
      "hrtf_database",
      "hrtf_subject_id",
      "hrtf_filter_id",
      "near_field_compensation",
      "ild_itd_policy",
      "headphones_model",
      "audio_interface_model",
      "speaker_array_id",
      "speaker_model",
      "speaker_count",
      "speaker_array_layout",
      "speaker_switch_sequence",
      "speaker_switch_times_ms",
      "speaker_switch_channels",
      "speaker_switch_gains",
      "speaker_source_channel",
      "room_acoustics",
      "reverb_brir_policy",
      "drr_iacc_policy",
      "renderer_equivalence_boundary",
      "visual_stimulus_type",
      "visual_motion_profile",
      "visual_start_distance_cm",
      "visual_end_distance_cm",
      "visual_renderer_engine",
      "visual_display_device",
      "mixed_reality_context",
      "body_rendering_mode",
      "audiovisual_synchrony_policy",
      "mixed_reality_equivalence_boundary",
    ],
    "renderer_or_apparatus",
  ),
  ...parent(
    [
      "trial_row_count",
      "row_ids",
      "row_labels",
      "row_order",
      "row_audio_tactile_percentage",
      "row_catch_percentage",
      "row_baseline_percentage",
      "row_soa_overrides_ms",
      "row_spatial_overrides_cm",
      "sequence_elements",
      "source_alternatives",
      "sequence_variant_count",
      "sequence_variant_keys",
    ],
    "trial_rows_families",
  ),
  ...parent(["condition_intermixing"], "condition_intermixing"),
  ...parent(["blocked_or_random_order"], "blocked_or_random_order"),
  ...parent(
    [
      "jitter_values_ms",
      "jitter_randomized",
      "iti_policy",
      "iti_values_or_range_ms",
      "iti_distribution",
      "pre_sound_silence_ms",
      "post_sound_silence_ms",
      "foreperiod_ms",
    ],
    "iti_jitter_policy",
  ),
  ...parent(["task_sequence_rules", "hazard_control_policy", "expectancy_control_role"], "task_sequence_rules"),
  ...parent(
    [
      "response_window_anchor",
      "response_window_min_ms",
      "response_window_max_ms",
      "online_timeout_ms",
    ],
    "response_window",
  ),
  ...parent(
    [
      "response_required_by_trial_type",
      "expected_response",
      "response_rule",
      "target_role",
      "response_mode",
      "response_choice_set",
      "correct_response",
      "response_scoring_policy",
      "response_capture_device",
      "response_input_modality",
      "voice_key_enabled",
      "voice_key_response_label",
      "voice_key_threshold",
      "voice_key_latency_correction_ms",
      "correctness_rule",
    ],
    "task_sequence_rules",
  ),
  ...parent(
    [
      "tactile_present",
      "tactile_modality",
      "stimulator_model",
      "tactile_site",
      "tactile_body_anchor",
      "tactile_side",
      "tactile_channel",
      "channel_map",
      "cue_duration_ms",
      "pulse_duration_ms",
      "waveform_shape",
      "frequency_hz",
      "amplitude",
      "intensity",
      "intensity_unit",
      "calibration_method",
      "threshold_reference",
      "electrode_site",
      "tactile_source_or_delivery",
      "external_trigger_required",
      "external_trigger_modality",
      "external_trigger_role",
      "external_trigger_code",
      "external_trigger_tolerance_ms",
      "external_trigger_channel",
    ],
    "tactile_stimulus",
  ),
  ...parent(
    [
      "soa_values_ms",
      "soa_reference_anchor",
      "soa_sign_convention",
      "spatial_values_cm",
      "pair_spatial_values_with_soas",
      "distance_at_touch_values_cm",
    ],
    "soa_table",
  ),
  ...parent(["baseline_enabled", "baseline_strategy", "baseline_custom_trial_mode"], "baseline_strategy"),
  ...parent(["baseline_soa_values_ms", "baseline_timing_reference"], "baseline_timing"),
  ...parent(["catch_enabled", "catch_type", "auditory_only_enabled"], "catch_trial_type"),
  ...parent(
    [
      "repetitions_per_condition",
      "repetition_defaults_by_family",
      "repetition_overrides_by_folder",
      "repetition_overrides_by_file",
      "fractional_repetition_policy",
      "fractional_balance_seed",
      "exact_family_counts",
    ],
    "repetitions_per_tactile_soa_condition",
  ),
  ...parent(["baseline_count_exact", "baseline_percentage", "baseline_crosses_sequence_variants"], "baseline_count"),
  ...parent(["catch_count_exact", "catch_percentage", "catch_crosses_sequence_variants"], "catch_count"),
  ...parent(["auditory_only_count_exact", "auditory_only_percentage", "auditory_only_crosses_sequence_variants"], "catch_count"),
  ...parent(["total_trial_count", "reported_or_target_playback_duration_s"], "total_trial_count"),
  ...parent(["block_count"], "block_count"),
  ...parent(
    [
      "trial_randomization_strategy",
      "block_order_randomization",
      "max_consecutive_same_trial_type",
      "row_order_constraints",
      "within_family_queue_policy",
      "condition_blocking_or_intermixing",
    ],
    "blocked_or_random_order",
  ),
];

const auditParentsByKey = new Map();
for (const [key, parents] of CURRENT_AUDIT_PARENT_ENTRIES) {
  auditParentsByKey.set(key, [...new Set([...(auditParentsByKey.get(key) || []), ...parents])]);
}

const FIRST_CLASS_KEYS = new Set([
  "stimulus_modality_set",
  "source_count",
  "source_labels",
  "source_kind",
  "import_render_mode",
  "source_motion_mode",
  "trajectory_count",
  "trajectory_labels",
  "trajectory_family",
  "trajectory_direction",
  "coordinate_mode",
  "coordinate_frame",
  "start_distance_cm",
  "end_distance_cm",
  "path_length_m",
  "speed_mps",
  "movement_duration_ms",
  "pre_hold_ms",
  "post_hold_ms",
  "inverse_square_enabled",
  "attenuation_gain_law",
  "audio_output_mode",
  "level_mode",
  "level_calibration_mode",
  "start_spl_db",
  "end_spl_db",
  "instruction_offset_db",
  "peak_ceiling_dbfs",
  "trial_row_count",
  "row_ids",
  "row_labels",
  "row_order",
  "sequence_elements",
  "source_alternatives",
  "sequence_variant_count",
  "sequence_variant_keys",
  "jitter_values_ms",
  "jitter_randomized",
  "condition_intermixing",
  "blocked_or_random_order",
  "tactile_present",
  "tactile_site",
  "tactile_side",
  "soa_values_ms",
  "spatial_values_cm",
  "pair_spatial_values_with_soas",
  "baseline_enabled",
  "baseline_strategy",
  "baseline_soa_values_ms",
  "baseline_custom_trial_mode",
  "catch_enabled",
  "auditory_only_enabled",
  "repetitions_per_condition",
  "repetition_defaults_by_family",
  "repetition_overrides_by_folder",
  "repetition_overrides_by_file",
  "baseline_count_exact",
  "baseline_percentage",
  "catch_count_exact",
  "catch_percentage",
  "block_count",
  "block_labels",
  "block_stimulus_types",
  "repeat_trial_pool_per_block",
  "distribute_trial_pool_across_blocks",
  "trial_randomization_strategy",
  "block_order_randomization",
  "max_consecutive_same_trial_type",
  "row_order_constraints",
  "random_seed",
  "part_count",
  "part_labels",
  "part_block_membership",
  "instruction_slots_enabled",
  "instruction_slot_labels",
  "instruction_audio_identity",
  "instruction_continue_modes",
  "instruction_delay_ms",
  "instruction_button_labels",
  "participant_order_seed",
  "order_preview_count",
  "profile_finalization_policy",
]);

const FREEFORM_KEYS = new Set([
  "population_scope",
  "group_labels",
  "condition_labels",
  "within_subject_factors",
  "between_subject_factors",
  "session_timepoints",
  "assignment_counterbalancing",
  "inclusion_criteria",
  "exclusion_criteria",
  "eligibility_screening",
  "intervention_training",
  "tool_condition",
  "locomotion_condition",
  "social_clinical_context",
  "semantic_valence_class",
  "source_origin_generation_method",
  "generation_software_version",
  "source_profile",
  "renderer_version",
  "headphones_model",
  "audio_interface_model",
  "speaker_array_id",
  "speaker_model",
  "speaker_array_layout",
  "room_acoustics",
  "visual_stimulus_type",
  "visual_motion_profile",
  "visual_display_device",
  "mixed_reality_context",
  "body_rendering_mode",
  "tactile_modality",
  "stimulator_model",
  "electrode_site",
  "tactile_source_or_delivery",
  "hazard_control_policy",
  "expectancy_control_role",
]);

const DERIVED_KEYS = new Set([
  "movement_duration_ms",
  "exact_family_counts",
  "total_trial_count",
  "reported_or_target_playback_duration_s",
  "per_block_trial_counts",
  "per_block_duration_estimates",
]);

const STRUCTURAL_GAP_KEYS = new Set([
  "planned_sample_n",
  "elevation_start_deg",
  "elevation_end_deg",
  "speaker_switch_sequence",
  "speaker_switch_times_ms",
  "speaker_switch_channels",
  "speaker_switch_gains",
  "speaker_source_channel",
  "visual_start_distance_cm",
  "visual_end_distance_cm",
  "visual_speed_cm_s",
  "visual_duration_ms",
  "visual_renderer_engine",
  "audiovisual_synchrony_policy",
  "mixed_reality_equivalence_boundary",
]);

const FIXED_POLICY_KEYS = new Set(["participant_code_policy"]);

function provisionalRoutingHint(groupDefinition, key) {
  if (STRUCTURAL_GAP_KEYS.has(key)) return "unsupported_structural_gap";
  if (FIXED_POLICY_KEYS.has(key)) return "fixed_policy_not_configurable";
  if (DERIVED_KEYS.has(key)) return "derived_materialized";
  if (FREEFORM_KEYS.has(key)) return "freeform_metadata_only";
  if (FIRST_CLASS_KEYS.has(key)) return "first_class_gui";
  return groupDefinition.defaultSupport;
}

function inferredUnit(key) {
  if (key.endsWith("_ms")) return "ms";
  if (key.endsWith("_s")) return "s";
  if (key.endsWith("_hz")) return "Hz";
  if (key.endsWith("_mps")) return "m/s";
  if (key.endsWith("_cm_s")) return "cm/s";
  if (key.endsWith("_cm")) return "cm";
  if (key.endsWith("_m")) return "m";
  if (key.endsWith("_deg")) return "degree";
  if (key.endsWith("_dbfs")) return "dBFS";
  if (key.endsWith("_db")) return "dB";
  if (key.endsWith("_percent")) return "%";
  return "";
}

function inferredShape(key, repeatableEntity) {
  if (
    key.includes("_labels") ||
    key.includes("_values") ||
    key.includes("_positions") ||
    key.includes("_factors") ||
    key.includes("_criteria") ||
    key.includes("_terms") ||
    key.includes("_set") ||
    key.includes("_mapping") ||
    key.includes("_sequence") ||
    key.includes("_overrides") ||
    key.includes("_membership") ||
    key.includes("_forms")
  ) {
    return "array_or_mapping";
  }
  if (
    key.endsWith("_enabled") ||
    key.endsWith("_required") ||
    key.startsWith("include_") ||
    key.startsWith("pair_") ||
    key.startsWith("repeat_") ||
    key.startsWith("distribute_") ||
    key.startsWith("catch_crosses_") ||
    key.startsWith("baseline_crosses_") ||
    key.startsWith("auditory_only_crosses_")
  ) {
    return "boolean";
  }
  if (inferredUnit(key) || key.endsWith("_count") || key.endsWith("_n") || key === "alpha") {
    return repeatableEntity ? "number_or_number_array" : "number";
  }
  return repeatableEntity ? "scalar_or_array" : "scalar";
}

export const PAPER_PARAMETERS = PAPER_PARAMETER_GROUPS.flatMap((groupDefinition) =>
  groupDefinition.keys.map((key) => ({
    parameterId: `${groupDefinition.prefix}.${key}`,
    key,
    groupId: groupDefinition.id,
    groupLabel: groupDefinition.label,
    segment: groupDefinition.segment,
    repeatableEntity: groupDefinition.repeatableEntity,
    valueShape: inferredShape(key, groupDefinition.repeatableEntity),
    expectedUnit: inferredUnit(key),
    currentAuditParents: auditParentsByKey.get(key) || [],
    provisionalRoutingHint: provisionalRoutingHint(groupDefinition, key),
    toolkitPath: groupDefinition.toolkitPath,
  })),
);

if (PAPER_PARAMETERS.length !== 281) {
  throw new Error(`Expected 281 proposed paper-dependent target leaves, found ${PAPER_PARAMETERS.length}`);
}

const parameterIds = new Set(PAPER_PARAMETERS.map((parameter) => parameter.parameterId));
if (parameterIds.size !== PAPER_PARAMETERS.length) {
  throw new Error("Duplicate proposed target parameter IDs detected");
}

export const ORIENTATION_EVIDENCE_COLUMNS = [
  "orientation_raw_visual_clue",
  "orientation_participant_facing_vector",
  "orientation_speaker_source_vector",
  "orientation_face_source_relation",
  "orientation_body_relative_translation",
  "orientation_approximation_grade",
  "orientation_unsupported_labels",
];

export const VISUALIZATION_COLUMNS = [
  "study_row_id",
  "visualization_id",
  "figure_table_panel",
  "visualization_type",
  "confirmation_status",
  "x_encoding",
  "x_values",
  "x_unit",
  "y_metric",
  "y_values",
  "y_unit",
  "model_family",
  "model_parameters",
  "fit_statistics",
  "boundary_index_definition",
  "boundary_index_value",
  "boundary_index_unit",
  "facets",
  "uncertainty_encoding",
  "visual_parameter_check",
  "evidence_class",
  "field_status",
  "review_note",
];

export const PROVISIONAL_ROUTING_HINTS = [
  "first_class_gui",
  "backend_schema_only",
  "runtime_only",
  "analysis_only",
  "calibration_only",
  "freeform_metadata_only",
  "derived_materialized",
  "fixed_policy_not_configurable",
  "proxy_or_substitution",
  "unsupported_structural_gap",
  "not_assessed",
];
